### ISSUE TITLE
AnyPyTools - KeyError 

### ISSUE THREAD

**Issue by ogulcanguldeniz** [AnyBody-Research-Group/AnyPyTools#23]
Hello again, 

Its Ogulcan, really appreciated your support! Like you suggested I tried everything and now I am opening a new issue. As a summary, I do have a usb drive with anybody setup, anaconda setup, anybody license file and model we are using. I am using same usb drive to install all of those softwares and using the same model, all other computers run the code except mine, I am getting KeyError everytime. So like you said it is not a problem caused by model differences. I

If you need I can provide anything you need to solve this issue. Thank you for your support once again! Hope to solve this problem as soon as possible. 

Ogulcan Guldeniz

**Comment by melund** [comment]
I think we solved this by email right. Otherwise feel free to reopen.
