### ISSUE TITLE
SetValue does not work as expected

### ISSUE THREAD

**Issue by sebastianskejoe** [AnyBody-Research-Group/AnyPyTools#30]
Setting value of Data of an AnyFunInterpol through SetValue, does not work as expected.
I have this AnyScript:
```AnyFunInterpol ErrorFun = {
  T = {0, 0.016, 0.024, 1};
  Data = DesignVar({{<DATA>}});
  Type = PiecewiseLinear;
};
```
and this Python-code:
```
values = ["{{0,0,0,0}}", "{{0.01, 0.01, 0, 0}}", "{{0.02, 0.02, 0, 0}}"];
macro = [
    Load('main.any'),
    SetValue('Main.Model.ErrorFun.Data', values),
    OperationRun('Main.RunApplication'),
    Dump('Main.Study.Output.Model.Dist.Pos'),
    Dump('Main.Model.ErrorFun.Data')
]
macro_list = AnyMacro(macro, number_of_macros=len(values))

filevalues_macro = [
    Load('main.any'),
    OperationRun('Main.RunApplication'),
    Dump('Main.Study.Output.Model.Dist.Pos'),
    Dump('Main.Model.ErrorFun.Data')
]
baseline_macro = AnyMacro(baseline)

app = AnyPyProcess(num_process = 4)
results = app.start_macro(macro_list)
fv_results = app.start_macro(AnyMacro(filevalues_macro))

for result in results:
    plt.plot(result['Main.Study.Output.Model.Dist.Pos'], label=result['Main.Model.ErrorFun.Data'])

lbl = "File values: ["+", ".join(str(x) for x in fv_results[0]["Main.Model.ErrorFun.Data"][0])+"]"
plt.plot(fv_results[0]['Main.Study.Output.Model.Dist.Pos'], "--", label=lbl)

plt.legend()
plt.show()
```
Setting <DATA> to 0,0,0,0 gives this plot: http://pasteall.org/pic/show.php?id=119069
Setting <DATA> to 0.01, 0.01, 0, 0 gives this plot: http://pasteall.org/pic/show.php?id=119070
Setting <DATA> to 0.02, 0.02, 0, 0 gives this plot: http://pasteall.org/pic/show.php?id=119071

I would have expected that the solid lines were the same on all plots.

**Comment by melund** [comment]
@sebastianskejoe 

I don't there is a problem with AnyPyTools here:

```
import numpy as np
from anypytools import AnyPyProcess
from anypytools.macro_commands import SetValue, Dump, Load, OperationRun, UpdateValues

bugmodel = """
Main = {
  AnyFunInterpol ifun = {
     Data = {{0,0.8,1.6}};
     T = {0,0.5,1};
     Type = Bezier;
     //Type = PiecewiseLinear;
  };
  
  AnyBodyStudy study = {
      Gravity = {0,-9.82, 0};
      nStep = 10;
      AnyFloat test = .ifun(t);
  };
};
"""
with open('bugmodel.any', 'w') as f:
    f.write(bugmodel)

values = [
    np.array([[0,0,0]]),
]

macrolist = [
    [Load('bugmodel.any'), 
     OperationRun('Main.study.Kinematics'),
     Dump('Main.study.Output.test')],
    [Load('bugmodel.any'), 
     SetValue('Main.ifun.Data', values),
     OperationRun('Main.study.Kinematics'),
     Dump('Main.study.Output.test')],
]

app = AnyPyProcess()
app.start_macro(macrolist)

```

which gives: 

```
[{'Main.study.Output.test': 
    array([[ 0.        ],
           [ 0.17777778],
           [ 0.35555556],
           [ 0.53333333],
           [ 0.71111111],
           [ 0.88888889],
           [ 1.0666667 ],
           [ 1.2444444 ],
           [ 1.4222222 ],
           [ 1.6       ]])},
 {'Main.study.Output.test': 
    array([[ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.],
           [ 0.]])}]
```

But if I change the interpolation type to PiecewiseLinear, then the output looks weird. I think that must be a bug in AnyBody. Can you try to do your operation directly in the AnyBody GUI and see if you also get the error there? 

Btw. Just a tip. You can specify your values as lists of numpy arrays. e.g. 
```
values = [np.array([[0,0,0]]), np.array([[0.01,0.01,0.01]]), np.array([[0.02,0.02,0.02]])]
```
That should be easier to work with.

**Comment by melund** [comment]
@sebastianskejoe I have dug a bit deeper. This definitely a bug in the AnyFunInterpol class in AnyBody. I think it only occurs when interpolation is set to `PiecewiseLinear`, so maybe you can solve the problem by switching interpolation type. Otherwise, I have no good suggestions for you.

**Comment by melund** [comment]
Feel free to close this issue if you agree.

**Comment by melund** [comment]
@sebastianskejoe I think I have found a workaround, that will allow you to use the `PiecewiseLinear` function.  You can force the right-hand side of `Data = {{.....}}` to be evaluated later by adding the following:

```
Data = (1+0*T[0]) + {{ ......}};
```

It basically forces AnyBody to consider the variable to be dependent on something which is evalutated later. That will ensure that new values in `Data` will be picked up when you use the "SetValue" operation. 

Hope this helps you.

**Comment by sebastianskejoe** [comment]
@melund The hack you suggested works - thanks a lot! Should I report the AnyBody-bug somewhere?

**Comment by melund** [comment]
I have already reported it, so don't worry about that. I don't know how easy it will be to fix, though. Seems a bit fundamental...

**Comment by sebastianskejoe** [comment]
No worries, the workaround will work just fine for now. Again, thanks for the quick reply :-)
