### ISSUE TITLE
get_anybodycon_path() doesn't check if file exists

### ISSUE THREAD

**Issue by sebastianskejoe** [AnyBody-Research-Group/AnyPyTools#36]
get_anybodycon_path() only checks if the path is set in the registry, but not whether the given path actually exists. This results in errors without an error message if the path is empty. It would be nice to check if the path points to an existing file and throw an exception if it doesn't.

The relevant method is [here](https://github.com/AnyBody-Research-Group/AnyPyTools/blob/master/anypytools/tools.py#L404).

**Comment by melund** [comment]
Thanks, @sebastianskejoe. This is definitely something that could be improved. You are welcome to make a pull request with a fix if you are up for it. Otherwise, I may fix this doing the Christmas holiday.

**Comment by sebastianskejoe** [comment]
Pull request submitted (#37).

**Comment by sebastianskejoe** [comment]
Probably shouldn't be closed until the pull request is merged. Reopening.

**Comment by melund** [comment]
I think this is fixed
