### ISSUE TITLE
Could not locate AnyBody in registry

### ISSUE THREAD

**Issue by elnormo** [AnyBody-Research-Group/AnyPyTools#92]
I'm running AnyPyTools as a package in an Anaconda environment. When I try to run the first commands of the AnyPyTools "getting started" jupyter notebook, I get an error that says "Could not locate AnyBody in registry". Any ideas on how to deal with that?

I tried uninstalling & re-installing AnyPyTools, with a shutdown in between, but still get the same error. Also, I can't find a separate AnyBody package.

### Version info:

* conda version : 4.10.3
* conda-build version : 3.21.6
* python version : 3.8.12.final.0
* anypytools: version = 1.7.5 build=py38haa244fe_1 channel=conda-forge
* Windows 10 Version = 10.0.18363 Build = 18363

### code 
(from http://localhost:8888/notebooks/01_Getting_started_with_anypytools.ipynb)
```
from anypytools import AnyPyProcess 
    app = AnyPyProcess()
```

### Error message:
```
 OSError: Could not locate AnyBody in registry
```

### Trace:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~\Anaconda3\lib\site-packages\anypytools\tools.py in get_anybodycon_path()
    461     try:
--> 462         abpath = winreg.QueryValue(
    463             winreg.HKEY_CLASSES_ROOT, "AnyBody.AnyScript\\shell\\open\\command"

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11000/586603320.py in <module>
      1 from anypytools import AnyPyProcess
----> 2 app = AnyPyProcess()

~\Anaconda3\lib\site-packages\anypytools\abcutils.py in __init__(self, num_processes, anybodycon_path, timeout, silent, ignore_errors, warnings_to_include, fatal_warnings, return_task_info, keep_logfiles, logfile_prefix, python_env, debug_mode, use_gui, priority, **kwargs)
    537 
    538         if anybodycon_path is None:
--> 539             anybodycon_path = get_anybodycon_path()
    540         anybodycon_path = Path(anybodycon_path)
    541         if use_gui:

~\Anaconda3\lib\site-packages\anypytools\tools.py in get_anybodycon_path()
    464         )
    465     except WindowsError:
--> 466         raise WindowsError("Could not locate AnyBody in registry")
    467     abpath = abpath.rsplit(" ", 1)[0].strip('"')
    468     abpath = os.path.join(os.path.dirname(abpath), "AnyBodyCon.exe")

OSError: Could not locate AnyBody in registry
```

**Comment by melund** [comment]
@elnormo. AnyPyTools is a utility to work the AnyBody Modeling System from Python. So you need to have AnyBody installed. 

AnyBody is a state-of-the-art commercial modeling system for biomechanics. So AnyPyTools will not help you much unless you or your University has a license for AnyBody.

**Comment by elnormo** [comment]
Thanks for the info. I looked at the AnyBody site and didn't understand why I would need licensed software. I don;t get how this got into my vanilla Anaconda install or my COBRApy install. COBRA is for metabolic flux analysis, not musculoskeletal modelling! 

I'm having a number of issues with missing packages, maybe I installed by mistake along with the other packages. Anyway, thanks for the quick response.

**Comment by melund** [comment]
It doesn't sound like you do musculoskeletal modeling so probably doesn't need AnyPyTools or AnyBody. Just out of curiosity how did you get AnyPyTools. Did you instsll it yourself or did it come as a dependency to one of your other packages?

**Comment by elnormo** [comment]
I believe I installed it myself. I was running some unit tests and got a bunch of errors saying this and that was not found so I had to install a bunch of additional packages. I must have installed anypytools by error. I uninstalled it and now I'm passing my unit tests.
